# Generated by Django 6.0 on 2025-12-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_ext', models.CharField(blank=True, max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('extracted_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('char_count', models.IntegerField(default=0)),
                ('document_type', models.CharField(default='other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
