# Generated by Django 6.0 on 2026-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='queued', max_length=20),
        ),
    ]
