# Generated by Django 6.0 on 2026-01-14 07:09

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_error_document_processed_at_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_document),
        ),
    ]
